### ISSUE TITLE
BUG: Unintended appearence of [!TIP]

### ISSUE THREAD

**Issue by bagustris** [abuibrahim2/quranlookup#20]
Thank you for the great plugin @abuibrahim2 . I have the following issue using the latest Obsidian. The Al-quran text still apears but it has preceding `> [!TIP]+` text. See image below.

![image](https://github.com/abuibrahim2/quranlookup/assets/3158361/f6c876cc-e69d-4132-b586-aa2bcc82679b)

I think that is unintended behavior and due to recent updates of Obsidian.

**Comment by fauzaanu** [comment]
I understand what you are trying to do, but i believe the plugin expects you to keep the verse on a new line as it's using callouts and I don't think callouts can be in the middle of a sentence like that.

We Could possibly add an option to send the verse to a new line if it's in a sentence but again if there is a word next to it this word would go below the callout.

**Comment by abuibrahim2** [comment]
This is true. One thing that could be done is have the call out container be optional based on a toggle in the settings.

I have some code that uses a table as a container rather than a call out, so different virtualization style options could work.

**Comment by fauzaanu** [comment]
A better format would be perhaps to not replace the ayah and leave the line as is and send the verse to the next line.

I believe the format tried in this screenshot goes like this:

In 1:1 allah says

[Verse]


And because the plugin is replacing the 1:1 we have bad formatting and the rest of the sentence ( allah says) is going down.

---

As a separate idea, tables will be great too!

**Comment by abuibrahim2** [comment]
I've added a few container options in the latest release 

- text only
- markdown table
- obsidian callout

In cases where you just want the text now you can get that via text only option
